#!/usr/bin/env node
// tools/build-3d.mjs — bundles lib/scene3d/index.js with three.js into the
// lazy chunk dist/explainers-3d.v1.js (ESM, tree-shaken, minified, es2020)
// with esbuild from tools/node_modules, and refreshes dist/integrity.json.
// The chunk is a dynamic import() of the runtime, so no <script> carries its
// hash; the manifest entry exists for the deploy check and the tests.
// Run: node tools/build-3d.mjs [--check]   (--check exits 1 when stale)
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { writeIntegrity, INTEGRITY_FILE } from './integrity.mjs';

export const CHUNK_VERSION = '1.0.0';
export const OUTFILE = 'dist/explainers-3d.v1.js';
export const ENTRY = 'lib/scene3d/index.js';
export const GZIP_BUDGET = 200 * 1000;

const toolsDir = path.dirname(fileURLToPath(import.meta.url));
export const root = path.resolve(toolsDir, '..');
const require = createRequire(path.join(toolsDir, 'package.json'));

export const gzipSize = (text) => gzipSync(Buffer.from(text), { level: 9 }).length;

// Returns { code, threeVersion } without touching dist/.
export async function buildChunk({ minify = true } = {}) {
  const { build } = await import(require.resolve('esbuild'));
  const threeVersion = JSON.parse(fs.readFileSync(path.join(toolsDir, 'node_modules/three/package.json'), 'utf8')).version;
  const banner = [
    `// explainers-3d v${CHUNK_VERSION} — GENERATED by tools/build-3d.mjs from lib/scene3d/ + three ${threeVersion} (MIT); do not edit.`,
    '// Lazy ESM chunk: imported by dist/explainers-runtime.v1.js on the first approach of a scene3d figure. Contract: DESIGN.md "Phase 3 status".',
  ].join('\n');
  const result = await build({
    entryPoints: [path.join(root, ENTRY)],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    minify,
    treeShaking: true,
    legalComments: 'none',
    logLevel: 'warning',
    nodePaths: [path.join(toolsDir, 'node_modules')],
    banner: { js: banner },
    define: { __THREE_DEVTOOLS__: 'undefined' },
  });
  return { code: stripTrailingWhitespace(result.outputFiles[0].text), threeVersion };
}

// The repo's pre-commit hook refuses trailing whitespace anywhere. In the
// minified chunk it occurs only inside three's GLSL template literals (lines
// such as `#if defined( USE_CLEARCOAT ) `), where GLSL ignores it, so the
// build strips it. A template literal that spans lines is exactly where a
// line ending can sit inside a string, and no shader depends on a trailing
// space or tab before its newline.
export function stripTrailingWhitespace(code) {
  return code.replace(/[ \t]+$/gm, '');
}

const invoked = process.argv[1] && /build-3d\.mjs$/.test(process.argv[1]);
if (invoked) {
  const { code, threeVersion } = await buildChunk();
  const file = path.join(root, OUTFILE);
  const gz = gzipSize(code);
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (current !== code) { console.error(`${OUTFILE} is stale; run: node tools/build-3d.mjs`); process.exit(1); }
    if (writeIntegrity(root, { check: true }).changed) { console.error(`${INTEGRITY_FILE} is stale; run: node tools/build-3d.mjs`); process.exit(1); }
    console.log(`${OUTFILE} current (${code.length} bytes, ${gz} gzip, three ${threeVersion})`);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, code);
    console.log(`wrote ${OUTFILE}: ${code.length} bytes, ${gz} gzip (three ${threeVersion}; budget ${GZIP_BUDGET} gzip)`);
    if (gz > GZIP_BUDGET) { console.error(`${OUTFILE} exceeds the ${GZIP_BUDGET} byte gzip budget`); process.exit(1); }
    const { changed } = writeIntegrity(root);
    console.log(changed ? `wrote ${INTEGRITY_FILE}; run: node tools/explainers.cjs build articles/*/index.html` : `${INTEGRITY_FILE} current`);
  }
}
