#!/usr/bin/env node
// Library-maintainer step (needs `npm install` in tools/ once):
//   1. bundle tools/src/cli.mjs + lib/ + parse5 + katex -> tools/explainers.cjs
//   2. vendor KaTeX's CSS and woff2 fonts -> assets/katex/
//   3. regenerate the generated sections of DESIGN.md
// Articles never need this; they run the committed tools/explainers.cjs.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { updateDesignDoc } from './gen-docs.mjs';

const toolsDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(toolsDir, '..');
const read = (p) => fs.readFileSync(p, 'utf8');
const pkgVersion = (name) => JSON.parse(read(path.join(toolsDir, 'node_modules', name, 'package.json'))).version;

const pins = JSON.parse(read(path.join(toolsDir, 'package.json'))).devDependencies;
const versions = { cli: '1.0.0', katex: pkgVersion('katex'), parse5: pkgVersion('parse5'), esbuild: pkgVersion('esbuild') };
for (const [name, pinned] of Object.entries(pins)) {
  if (versions[name] !== pinned) console.warn(`WARNING: ${name} ${versions[name]} is installed but tools/package.json pins ${pinned}; run npm install in tools/ and rebuild`);
}

const outfile = path.join(toolsDir, 'explainers.cjs');
await build({
  entryPoints: [path.join(toolsDir, 'src/cli.mjs')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  legalComments: 'none',
  logLevel: 'warning',
  define: { __EXPLAINERS_VERSIONS__: JSON.stringify(versions) },
  banner: {
    js: [
      '#!/usr/bin/env node',
      `// GENERATED by tools/build-cli.mjs — do not edit; rebuild with: cd tools && npm install && node build-cli.mjs`,
      `// bundles: ${Object.entries(versions).map(([k, v]) => `${k} ${v}`).join(', ')}`,
    ].join('\n'),
  },
});
fs.chmodSync(outfile, 0o755);
console.log(`wrote ${path.relative(root, outfile)} (${(fs.statSync(outfile).size / 1024).toFixed(0)} KiB)`);

// Vendor KaTeX CSS + woff2 fonts (the CSS references fonts/ relatively).
const katexDist = path.join(toolsDir, 'node_modules/katex/dist');
const assetsKatex = path.join(root, 'assets/katex');
fs.mkdirSync(path.join(assetsKatex, 'fonts'), { recursive: true });
fs.copyFileSync(path.join(katexDist, 'katex.min.css'), path.join(assetsKatex, 'katex.min.css'));
let fonts = 0;
for (const f of fs.readdirSync(path.join(katexDist, 'fonts'))) {
  if (f.endsWith('.woff2')) { fs.copyFileSync(path.join(katexDist, 'fonts', f), path.join(assetsKatex, 'fonts', f)); fonts++; }
}
fs.writeFileSync(path.join(assetsKatex, 'VERSION'), `katex ${versions.katex}\n`);
console.log(`vendored assets/katex/katex.min.css + ${fonts} woff2 fonts (katex ${versions.katex})`);

const changed = updateDesignDoc(path.join(root, 'DESIGN.md'));
console.log(changed ? 'DESIGN.md generated sections updated' : 'DESIGN.md generated sections already current');
